vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       products:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       model_images:
           uri_prefix: /images/models
           upload_destination: '%kernel.project_dir%/public/images/models'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       color_images:
           uri_prefix: /images/colors
           upload_destination: '%kernel.project_dir%/public/images/colors'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
